from enum import Enum

class Resultat(Enum):
  VICTOIRE = 1
  DEFAITE = 2
  EGALITE = 3
  EGALITE_VICTOIRE = 4
  EGALITE_DEFAITE = 5
  GRANDE_VICTOIRE = 6
  GRANDE_DEFAITE = 7
  PAS_VUE = 8
  NUL = 9
  BIEN = 10
  SAUVEGARDE = 11
  FIN = 12
