from enum import Enum

class Resultat(Enum):
  VICTOIRE = 1
  DEFAITE = 2
  EGALITE = 3
  EGALITE_VICTOIRE = 4
  EGALITE_DEFAITE = 5
  GRANDE_VICTOIRE = 6
  GRANDE_DEFAITE = 7
  PAS_VUE1 = 8
  PAS_VUE2 = 9
  PAS_VUE_LES_DEUX = 10
